account_id = "a7801a7bf9a0265dff24ea0358da5721"
name = "my-react-app"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-05-24"
